---
- name: "Update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "Remove dependencies which are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "install python for Ansible."
  become: yes
  apt:
    name: "python3-pip"
    update_cache: yes
    state: present

- name: "Install npm and nodejs"
  become: true
  apt:
    name: ["npm", "nodejs"]
    update_cache: yes
    state: latest

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present